version: '3.8'

services:
  eco-game-server:
    container_name: eco-game-server
    image: strangeloopgames/eco-game-server:latest
    restart: always
    # command: ["./EcoServer", "--nogui", "--userToken=YOUR_TOKEN"]
    command: ["./EcoServer", "--nogui", "--offline"]
    volumes:
      - ./mount/Storage/:/app/Storage/
      - ./mount/Configs/:/app/Configs/
    ports:
      - "3000:3000/udp"
      - "3001:3001/tcp"
